# Generated by Django 3.2.4 on 2021-11-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_fk_iduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
