# Generated by Django 3.2.4 on 2021-08-01 20:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='peso',
        ),
        migrations.AlterField(
            model_name='pet',
            name='coordenada',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(-46.65647647383157, -23.561051152327074)', srid=4326),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
