# Generated by Django 3.2.4 on 2021-07-15 10:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='coordenada',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=4326),
        ),
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(upload_to='pet'),
        ),
    ]
