# Generated by Django 3.2.4 on 2021-08-07 21:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='dataNascimento',
            new_name='dataPerdaEncontro',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='peso',
        ),
        migrations.AddField(
            model_name='pet',
            name='especie',
            field=models.IntegerField(choices=[(1, 'Cachorro'), (2, 'Gato'), (3, 'Outros')], default=1, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='coordenada',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(-46.65647647383157, -23.561051152327074)', srid=4326),
        ),
        migrations.AlterField(
            model_name='pet',
            name='encontradoPerdido',
            field=models.IntegerField(choices=[(1, 'Perdido'), (2, 'Encontrado')], default=1, verbose_name='EncontradoPerdido'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
