# Generated by Django 3.2.4 on 2021-06-21 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOCALIZACAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('rua', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=10)),
                ('num', models.IntegerField()),
                ('bairro', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='dataCadastro',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='status',
        ),
        migrations.AddField(
            model_name='pet',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='comprimento',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='dataNascimento',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='largura',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='observacoes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='cor',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='raca',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='ABRIGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('FK_idLocalizacao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.localizacao')),
                ('FK_idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='FK_idAbrigo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.abrigo'),
            preserve_default=False,
        ),
    ]
