# Generated by Django 3.2.4 on 2021-07-18 13:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210718_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='coordenada',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=4326),
        ),
    ]
