# Generated by Django 3.2.4 on 2021-07-18 14:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pet_coordenada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='coordenada',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(-46.65580414499566 -23.565801069428833)', srid=4326),
        ),
    ]
