# Generated by Django 3.2.4 on 2021-07-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pet_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(upload_to='pet'),
        ),
    ]
