# Generated by Django 3.2.4 on 2021-07-23 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pet_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='foto',
        ),
    ]
