# Generated by Django 3.2.4 on 2021-07-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_pet_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='foto',
            field=models.ImageField(null=True, upload_to='pet'),
        ),
    ]
